import { defineConfig } from 'vite-plus';

const toolIgnorePatterns = [
  '**/*.md',
  '.claude/**',
  '.pnpm-store/**',
  'coverage/**',
  'dist/**',
  '**/dist/**',
  'node_modules/**',
  '**/node_modules/**',
  'styles/**',
  'test-fixtures/**',
];

export default defineConfig({
  fmt: {
    ignorePatterns: toolIgnorePatterns,
    semi: true,
    singleQuote: true,
    sortPackageJson: true,
  },
  lint: {
    categories: {
      correctness: 'error',
      nursery: 'off',
      pedantic: 'off',
      restriction: 'error',
      style: 'error',
      suspicious: 'error',
    },
    ignorePatterns: toolIgnorePatterns,
    options: {
      reportUnusedDisableDirectives: 'error',
      typeAware: true,
      typeCheck: true,
    },
    plugins: ['typescript', 'import', 'vitest'],
    rules: {
      '@typescript-eslint/array-type': ['error', { default: 'generic' }],
      '@typescript-eslint/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-import-type-side-effects': 'error',
      '@typescript-eslint/explicit-function-return-type': 'off',
      complexity: ['error', 20],
      'import/consistent-type-specifier-style': 'off',
      'import/exports-last': 'off',
      'import/group-exports': 'off',
      'import/max-dependencies': ['error', { max: 15 }],
      'import/no-default-export': 'off',
      'import/no-named-export': 'off',
      'import/no-nodejs-modules': 'off',
      'import/no-relative-parent-imports': 'off',
      'import/prefer-default-export': 'off',
      'jest/require-hook': 'off',
      'max-depth': ['error', 4],
      'max-lines': ['error', 500],
      'max-lines-per-function': ['error', 75],
      'max-params': ['error', 4],
      'max-statements': 'off',
      'no-console': 'error',
      'no-else-return': 'error',
      'no-magic-numbers': ['error', { ignore: [0, 1, 4, 15, 20, 75, 500] }],
      'no-continue': 'off',
      'no-nested-ternary': 'error',
      'no-param-reassign': 'error',
      'no-ternary': 'off',
      'no-unneeded-ternary': 'error',
      'sort-imports': 'off',
      'sort-keys': 'off',
      'vitest/no-importing-vitest-globals': 'off',
    },
  },
  staged: {
    '*.{js,ts,tsx,jsx,json}': 'vp check --fix',
    '*.{md,mdx}': 'pnpm prose',
  },
  test: {
    exclude: ['**/node_modules/**', '**/dist/**'],
    include: ['packages/**/*.test.ts'],
  },
});
