import {
  baseConfig,
  composeLintConfigs,
  nodeRuntimeConfig,
  vitestConfig,
} from '@mplibunao/oxlint-standards';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vite-plus';

const toolIgnorePatterns = [
  '**/*.md',
  '.claude/**',
  '.pnpm-store/**',
  'coverage/**',
  'dist/**',
  '**/dist/**',
  'node_modules/**',
  '**/node_modules/**',
  'styles/**',
  'test-fixtures/**',
  // Generated by `pnpm gen:effective-config`; the generator owns its exact bytes.
  // Formatting would compact the arrays and flap the effective-config staleness gate.
  // The gate compares the committed file against raw generator output.
  'docs/references/effective-config.json',
];

export default defineConfig({
  fmt: {
    ignorePatterns: toolIgnorePatterns,
    semi: true,
    singleQuote: true,
    sortPackageJson: true,
  },
  lint: composeLintConfigs(
    baseConfig,
    vitestConfig,
    nodeRuntimeConfig,
    {
      ignorePatterns: toolIgnorePatterns,
    },
    {
      rules: {
        // backpressure is a published library/tooling monorepo with no natural @/ source root.
        // Alias rewriting would add build/runtime resolver complexity for package and script code.
        'import/no-relative-parent-imports': 'off',
      },
    },
    {
      overrides: [
        {
          files: ['packages/oxlint-standards/src/**'],
          rules: {
            'import/no-relative-parent-imports': 'error',
          },
        },
      ],
    },
  ),
  resolve: {
    alias: {
      '#oxlint-standards': fileURLToPath(
        new URL('./packages/oxlint-standards/src', import.meta.url),
      ),
    },
  },
  staged: {
    '*.{js,ts,tsx,jsx,json}': 'vp check --fix',
    '*.{md,mdx}': 'pnpm prose',
  },
  test: {
    exclude: ['**/node_modules/**', '**/dist/**'],
    include: ['packages/**/*.test.ts', 'scripts/**/*.test.ts'],
  },
});
