/* oxlint-disable max-lines -- The manifest is intentionally data-dense because it is the canonical machine-checkable catalog. */

export type RuleDomain = 'effect' | 'effect-react' | 'general' | 'boundaries' | 'lsp';
export type RuleDisposition =
  | 'ported'
  | 'reimplemented'
  | 'built-in'
  | 'LSP-delegated'
  | 'dropped'
  | 'not-implemented';
export type RuleSourceOwnership =
  | 'linteffect'
  | 'executor'
  | 'recon:effect-smol'
  | 'recon:t3code'
  | 'recon'
  | 'built-in'
  | 'LSP';
export type RuleTestSource = 'linteffect-fixture' | 't3code' | 'scenario-only' | 'none';
export type RuleParityStatus =
  | 'source-fixture-replay'
  | 'semantic-scenario-replay'
  | 'delegated'
  | 'not-applicable';
export type RuleGating =
  | 'effect-import'
  | 'effect-callee'
  | 'effect-react-import'
  | 'ungated-broad'
  | 'stack-neutral'
  | 'boundary';

export interface RuleManifestEntry {
  readonly name: string;
  readonly domain: RuleDomain;
  readonly sourcePresets: ReadonlyArray<string>;
  readonly severity: 'off' | 'info' | 'warning' | 'error';
  readonly implementationStatus: 'implemented' | 'not-implemented' | 'delegated';
  readonly testStatus: 'covered' | 'not-applicable';
  readonly parityStatus: RuleParityStatus;
  readonly disposition: RuleDisposition;
  readonly effectVersionSensitivity: string;
  readonly sourceOwnership: RuleSourceOwnership;
  readonly testSource: RuleTestSource;
  readonly gating: RuleGating;
  readonly presetEnabled: boolean;
  readonly note: string;
}

const sourceRule = (entry: RuleManifestEntry): RuleManifestEntry => entry;

const lspDelegatedCheck = (name: string): RuleManifestEntry =>
  sourceRule({
    name: `lsp/${name}`,
    domain: 'lsp',
    sourcePresets: [],
    severity: 'error',
    implementationStatus: 'delegated',
    testStatus: 'not-applicable',
    parityStatus: 'delegated',
    disposition: 'LSP-delegated',
    effectVersionSensitivity: 'type-aware semantic',
    sourceOwnership: 'LSP',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: false,
    note: '@effect/language-service owns this semantic/type-aware diagnostic.',
  });

const lspDelegatedChecks = (names: ReadonlyArray<string>): ReadonlyArray<RuleManifestEntry> =>
  names.map(lspDelegatedCheck);

// --- Authoring helpers ---
// Use these for new entries instead of sourceRule to avoid repeating boilerplate defaults.
// Existing entries use the older sourceRule helper and are not converted here.
// Partial conversion is intentional — converting all entries in bulk would make the diff unreviewable
// With no behavior difference between the two forms.

interface PortedScenarioRuleOptions {
  readonly name: string;
  readonly domain: RuleDomain;
  readonly sourcePresets: ReadonlyArray<string>;
  readonly severity: 'off' | 'info' | 'warning' | 'error';
  readonly gating: RuleGating;
  readonly presetEnabled: boolean;
  readonly note: string;
}

/**
 * Ported linteffect rule with semantic-scenario-replay coverage.
 * Hardcodes: ported / implemented / covered / semantic-scenario-replay / v4-primary structural / linteffect / testSource:none.
 */
export const portedScenarioRule = ({
  name,
  domain,
  sourcePresets,
  severity,
  gating,
  presetEnabled,
  note,
}: PortedScenarioRuleOptions): RuleManifestEntry => ({
  name,
  domain,
  sourcePresets,
  severity,
  implementationStatus: 'implemented',
  testStatus: 'covered',
  parityStatus: 'semantic-scenario-replay',
  disposition: 'ported',
  effectVersionSensitivity: 'v4-primary structural',
  sourceOwnership: 'linteffect',
  testSource: 'none',
  gating,
  presetEnabled,
  note,
});

interface PortedFixtureRuleOptions {
  readonly name: string;
  readonly domain: RuleDomain;
  readonly sourcePresets: ReadonlyArray<string>;
  readonly gating: RuleGating;
  readonly presetEnabled: boolean;
  readonly note: string;
}

/**
 * Ported linteffect rule tested via upstream source fixtures.
 * Hardcodes: ported / error / implemented / covered / source-fixture-replay / v4-primary structural / linteffect / linteffect-fixture.
 */
export const portedFixtureRule = ({
  name,
  domain,
  sourcePresets,
  gating,
  presetEnabled,
  note,
}: PortedFixtureRuleOptions): RuleManifestEntry => ({
  name,
  domain,
  sourcePresets,
  severity: 'error',
  implementationStatus: 'implemented',
  testStatus: 'covered',
  parityStatus: 'source-fixture-replay',
  disposition: 'ported',
  effectVersionSensitivity: 'v4-primary structural',
  sourceOwnership: 'linteffect',
  testSource: 'linteffect-fixture',
  gating,
  presetEnabled,
  note,
});

interface ReimplementedScenarioRuleOptions {
  readonly name: string;
  readonly domain: RuleDomain;
  readonly severity: 'off' | 'info' | 'warning' | 'error';
  readonly effectVersionSensitivity: string;
  readonly sourceOwnership: RuleSourceOwnership;
  readonly testSource: RuleTestSource;
  readonly gating: RuleGating;
  readonly presetEnabled: boolean;
  readonly note: string;
}

/**
 * Net-new or executor/recon reimplemented rule (no linteffect source).
 * Hardcodes: reimplemented / sourcePresets:[] / implemented / covered / semantic-scenario-replay.
 */
export const reimplementedScenarioRule = ({
  name,
  domain,
  severity,
  effectVersionSensitivity,
  sourceOwnership,
  testSource,
  gating,
  presetEnabled,
  note,
}: ReimplementedScenarioRuleOptions): RuleManifestEntry => ({
  name,
  domain,
  sourcePresets: [],
  severity,
  implementationStatus: 'implemented',
  testStatus: 'covered',
  parityStatus: 'semantic-scenario-replay',
  disposition: 'reimplemented',
  effectVersionSensitivity,
  sourceOwnership,
  testSource,
  gating,
  presetEnabled,
  note,
});

interface BuiltInRuleOptions {
  readonly name: string;
  readonly domain: RuleDomain;
  readonly severity: 'off' | 'info' | 'warning' | 'error';
  readonly gating: RuleGating;
  readonly presetEnabled: boolean;
  readonly note: string;
}

/**
 * Built-in oxlint rule included in a preset with no custom implementation.
 * Hardcodes: built-in / sourcePresets:[] / implemented / not-applicable / not-applicable / structural / built-in / none.
 */
export const builtInRule = ({
  name,
  domain,
  severity,
  gating,
  presetEnabled,
  note,
}: BuiltInRuleOptions): RuleManifestEntry => ({
  name,
  domain,
  sourcePresets: [],
  severity,
  implementationStatus: 'implemented',
  testStatus: 'not-applicable',
  parityStatus: 'not-applicable',
  disposition: 'built-in',
  effectVersionSensitivity: 'structural',
  sourceOwnership: 'built-in',
  testSource: 'none',
  gating,
  presetEnabled,
  note,
});

export const ruleManifest = [
  sourceRule({
    name: 'no-arrow-ladder',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-atom-registry-effect-sync',
    domain: 'effect-react',
    sourcePresets: ['web', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-branch-in-object',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-call-tower',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: false,
    note: 'Implemented and replay-covered, but omitted from presets because no-effect-call-in-effect-arg owns the overlapping shallow nested-call intent.',
  }),
  sourceRule({
    name: 'no-effect-all-step-sequencing',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-effect-as',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester and replay coverage.',
  }),
  sourceRule({
    name: 'no-effect-async',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-effect-bind',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-effect-call-in-effect-arg',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-effect-do',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-effect-fn-generator',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'not-implemented',
    testStatus: 'not-applicable',
    parityStatus: 'not-applicable',
    disposition: 'dropped',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: false,
    note: 'Effect.fn generator bodies are preferred traced units of logic.',
  }),
  sourceRule({
    name: 'no-effect-ladder',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-effect-never',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-effect-orElse-ladder',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-effect-side-effect-wrapper',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester and replay coverage.',
  }),
  sourceRule({
    name: 'no-effect-succeed-variable',
    domain: 'effect',
    sourcePresets: [],
    severity: 'warning',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-effect-sync-console',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-effect-type-alias',
    domain: 'effect',
    sourcePresets: ['ts-type', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-effect-wrapper-alias',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment. Ownership split: direct Effect.gen wrapper declarations (const arrow or function declaration returning Effect.gen) are intentionally excluded and owned by prefer-effect-fn; pipe(Effect.gen(...), ...) aliases remain owned by this rule.',
  }),
  sourceRule({
    name: 'no-family-collection-read',
    domain: 'effect-react',
    sourcePresets: ['web', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'source-fixture-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'linteffect-fixture',
    gating: 'effect-react-import',
    presetEnabled: true,
    note: 'Source-fixture-faithful structural port with RuleTester and replay coverage.',
  }),
  sourceRule({
    name: 'no-flatmap-ladder',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'warning',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-fromnullable-nullish-coalesce',
    domain: 'effect',
    sourcePresets: ['ts-type', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-if-statement',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'not-implemented',
    testStatus: 'not-applicable',
    parityStatus: 'not-applicable',
    disposition: 'dropped',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: false,
    note: 'Conflicts with gen-first posture; guards inside generators are allowed.',
  }),
  sourceRule({
    name: 'no-iife-wrapper',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-inline-runtime-provide',
    domain: 'effect-react',
    sourcePresets: ['web'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-manual-effect-channels',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-match-effect-branch',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-match-void-branch',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-model-overlay-cast',
    domain: 'effect',
    sourcePresets: ['ts-type', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'source-fixture-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'linteffect-fixture',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Source-fixture-faithful structural port with RuleTester and replay coverage.',
  }),
  sourceRule({
    name: 'no-naked-object-state-update',
    domain: 'effect-react',
    sourcePresets: ['web', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'source-fixture-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'linteffect-fixture',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Source-fixture-backed structural port. JSON.parse ownership is intentionally delegated to no-json-parse in composed presets so object-state update diagnostics stay focused on stringify/object-rebuild shapes.',
  }),
  sourceRule({
    name: 'no-nested-effect-call',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: false,
    note: 'Implemented and replay-covered, but omitted from presets because no-effect-ladder owns the overlapping deep nested-call intent.',
  }),
  sourceRule({
    name: 'no-nested-effect-gen',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-option-as',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-option-boolean-normalization',
    domain: 'effect',
    sourcePresets: ['ts-type', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-pipe-ladder',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-react-state',
    domain: 'effect-react',
    sourcePresets: ['web', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'ungated-broad',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-render-side-effects',
    domain: 'effect-react',
    sourcePresets: ['web', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-return-in-arrow',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'info',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester and replay coverage.',
  }),
  sourceRule({
    name: 'no-return-in-callback',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'info',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-return-null',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-runtime-runfork',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-string-sentinel-const',
    domain: 'effect',
    sourcePresets: ['ts-type', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-string-sentinel-return',
    domain: 'effect',
    sourcePresets: ['ts-type', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-switch-statement',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'source-fixture-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'linteffect-fixture',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Source-fixture-faithful structural port with RuleTester and replay coverage.',
  }),
  sourceRule({
    name: 'no-ternary',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'not-implemented',
    testStatus: 'not-applicable',
    parityStatus: 'not-applicable',
    disposition: 'dropped',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: false,
    note: 'Blanket ternary ban is too broad; general enables built-in no-nested-ternary instead.',
  }),
  sourceRule({
    name: 'no-try-catch',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'no-unknown-boolean-coercion-helper',
    domain: 'effect',
    sourcePresets: ['ts-type', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester and replay coverage.',
  }),
  sourceRule({
    name: 'no-wrapgraphql-catchall',
    domain: 'effect',
    sourcePresets: ['full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'prevent-dynamic-imports',
    domain: 'general',
    sourcePresets: ['core', 'full'],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'stack-neutral',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester and replay coverage.',
  }),
  sourceRule({
    name: 'warn-effect-sync-wrapper',
    domain: 'effect',
    sourcePresets: ['core', 'full'],
    severity: 'warning',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'ported',
    effectVersionSensitivity: 'v4-primary structural',
    sourceOwnership: 'linteffect',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural port with RuleTester coverage and preset assignment.',
  }),
  sourceRule({
    name: 'effect-no-multiple-provide',
    domain: 'effect',
    sourcePresets: [],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'reimplemented',
    effectVersionSensitivity: 'structural',
    sourceOwnership: 'recon',
    testSource: 'none',
    gating: 'effect-callee',
    presetEnabled: true,
    note: 'Net-new D3 rule; counts direct pipe provide steps with Effect namespace binding.',
  }),
  sourceRule({
    name: 'prefer-effect-predicate',
    domain: 'effect',
    sourcePresets: [],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'reimplemented',
    effectVersionSensitivity: 'structural',
    sourceOwnership: 'executor',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Executor-derived structural nullish predicate rule.',
  }),
  sourceRule({
    name: 'prefer-effect-fn',
    domain: 'effect',
    sourcePresets: [],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'reimplemented',
    effectVersionSensitivity: 'v4-primary Effect.gen wrapper shape',
    sourceOwnership: 'recon',
    testSource: 'scenario-only',
    gating: 'effect-callee',
    presetEnabled: true,
    note: 'Recon-derived gen-first rule: redundant wrappers around Effect.gen should become Effect.fn/fnUntraced.',
  }),
  sourceRule({
    name: 'no-barrel-import',
    domain: 'effect',
    sourcePresets: [],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'reimplemented',
    effectVersionSensitivity: 'structural',
    sourceOwnership: 'recon:effect-smol',
    testSource: 'scenario-only',
    gating: 'ungated-broad',
    presetEnabled: true,
    note: 'effect-smol scenario port: named and namespace value imports from effect only.',
  }),
  sourceRule({
    name: 'no-inline-schema-compile',
    domain: 'effect',
    sourcePresets: [],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'reimplemented',
    effectVersionSensitivity: 'structural',
    sourceOwnership: 'recon:t3code',
    testSource: 't3code',
    gating: 'effect-callee',
    presetEnabled: true,
    note: 't3code scenario port for inline Schema compiler calls inside function bodies.',
  }),
  sourceRule({
    name: 'no-cross-package-relative-imports',
    domain: 'boundaries',
    sourcePresets: [],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'reimplemented',
    effectVersionSensitivity: 'structural',
    sourceOwnership: 'executor',
    testSource: 'none',
    gating: 'boundary',
    presetEnabled: true,
    note: 'Executor-derived cross-package relative import rule.',
  }),
  sourceRule({
    name: 'no-redundant-primitive-cast',
    domain: 'general',
    sourcePresets: [],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'reimplemented',
    effectVersionSensitivity: 'structural',
    sourceOwnership: 'executor',
    testSource: 'none',
    gating: 'stack-neutral',
    presetEnabled: true,
    note: 'Executor-derived primitive as-cast rule.',
  }),
  sourceRule({
    name: 'no-effect-escape-hatch',
    domain: 'effect',
    sourcePresets: [],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'reimplemented',
    effectVersionSensitivity: 'structural',
    sourceOwnership: 'executor',
    testSource: 'none',
    gating: 'effect-callee',
    presetEnabled: true,
    note: 'Executor-derived Effect die/orDie escape-hatch rule.',
  }),
  sourceRule({
    name: 'no-double-cast',
    domain: 'general',
    sourcePresets: [],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'reimplemented',
    effectVersionSensitivity: 'structural',
    sourceOwnership: 'executor',
    testSource: 'none',
    gating: 'stack-neutral',
    presetEnabled: true,
    note: 'Executor-derived double cast rule.',
  }),
  sourceRule({
    name: 'no-ts-nocheck',
    domain: 'general',
    sourcePresets: [],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'reimplemented',
    effectVersionSensitivity: 'structural',
    sourceOwnership: 'executor',
    testSource: 'none',
    gating: 'stack-neutral',
    presetEnabled: true,
    note: 'Executor-derived ts-nocheck rule.',
  }),
  builtInRule({
    name: 'no-nested-ternary',
    domain: 'general',
    severity: 'error',
    gating: 'stack-neutral',
    presetEnabled: true,
    note: 'Built-in oxlint rule enabled instead of linteffect no-ternary.',
  }),
  sourceRule({
    name: 'no-json-parse',
    domain: 'effect',
    sourcePresets: [],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'reimplemented',
    effectVersionSensitivity: 'structural',
    sourceOwnership: 'executor',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural reimplementation with explicit replay branch matrix and RuleTester coverage.',
  }),
  sourceRule({
    name: 'prefer-schema-inferred-types',
    domain: 'effect',
    sourcePresets: [],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'reimplemented',
    effectVersionSensitivity: 'structural',
    sourceOwnership: 'executor',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural reimplementation with explicit replay branch matrix and RuleTester coverage.',
  }),
  sourceRule({
    name: 'no-promise-catch',
    domain: 'effect',
    sourcePresets: [],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'reimplemented',
    effectVersionSensitivity: 'structural',
    sourceOwnership: 'executor',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural reimplementation with explicit replay branch matrix and RuleTester coverage.',
  }),
  sourceRule({
    name: 'no-promise-reject',
    domain: 'effect',
    sourcePresets: [],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'reimplemented',
    effectVersionSensitivity: 'structural',
    sourceOwnership: 'executor',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural reimplementation with explicit replay branch matrix and RuleTester coverage.',
  }),
  sourceRule({
    name: 'no-instanceof-error',
    domain: 'effect',
    sourcePresets: [],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'reimplemented',
    effectVersionSensitivity: 'structural',
    sourceOwnership: 'executor',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural reimplementation with explicit replay branch matrix and RuleTester coverage.',
  }),
  sourceRule({
    name: 'no-instanceof-tagged-error',
    domain: 'effect',
    sourcePresets: [],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'reimplemented',
    effectVersionSensitivity: 'structural',
    sourceOwnership: 'executor',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural reimplementation with explicit replay branch matrix and RuleTester coverage.',
  }),
  sourceRule({
    name: 'no-manual-tag-check',
    domain: 'effect',
    sourcePresets: [],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'reimplemented',
    effectVersionSensitivity: 'structural',
    sourceOwnership: 'executor',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural reimplementation with explicit replay branch matrix and RuleTester coverage.',
  }),
  sourceRule({
    name: 'no-effect-internal-tags',
    domain: 'effect',
    sourcePresets: [],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'reimplemented',
    effectVersionSensitivity: 'structural',
    sourceOwnership: 'executor',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural reimplementation with explicit replay branch matrix and RuleTester coverage.',
  }),
  sourceRule({
    name: 'no-unknown-error-message',
    domain: 'effect',
    sourcePresets: [],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'reimplemented',
    effectVersionSensitivity: 'structural',
    sourceOwnership: 'executor',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural reimplementation with explicit replay branch matrix and RuleTester coverage.',
  }),
  sourceRule({
    name: 'prefer-yield-tagged-error',
    domain: 'effect',
    sourcePresets: [],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'reimplemented',
    effectVersionSensitivity: 'structural',
    sourceOwnership: 'executor',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural reimplementation with explicit replay branch matrix and RuleTester coverage.',
  }),
  sourceRule({
    name: 'no-redundant-error-factory',
    domain: 'effect',
    sourcePresets: [],
    severity: 'error',
    implementationStatus: 'implemented',
    testStatus: 'covered',
    parityStatus: 'semantic-scenario-replay',
    disposition: 'reimplemented',
    effectVersionSensitivity: 'structural',
    sourceOwnership: 'executor',
    testSource: 'none',
    gating: 'effect-import',
    presetEnabled: true,
    note: 'Scenario-covered structural reimplementation with explicit replay branch matrix and RuleTester coverage.',
  }),
  ...lspDelegatedChecks([
    'importFromBarrel',
    'missingEffectServiceDependency',
    'leakingRequirements',
    'unsafeEffectTypeAssertion',
    'instanceOfSchema',
    'globalDate',
    'globalRandom',
    'globalConsole',
    'globalFetch',
    'globalTimers',
    'preferSchemaOverJson',
    'schemaSyncInEffect',
    'cryptoRandomUUID',
  ]),
] as const satisfies ReadonlyArray<RuleManifestEntry>;

export const implementedCustomRuleNames = ruleManifest
  .filter(
    (entry) => entry.implementationStatus === 'implemented' && entry.disposition !== 'built-in',
  )
  .map((entry) => entry.name);
export const presetEnabledRuleNames = ruleManifest
  .filter((entry) => entry.presetEnabled)
  .map((entry) => entry.name);
export const lspOwnedChecks = ruleManifest
  .filter((entry) => entry.disposition === 'LSP-delegated')
  .map((entry) => entry.name.replace('lsp/', ''));
export const linteffectSourceRuleNames = ruleManifest
  .filter((entry) => entry.sourceOwnership === 'linteffect')
  .map((entry) => entry.name);

// --- Manifest query helpers ---
// Defined here (not in rule-manifest-selection.ts) so scripts can import via .ts extension;
// Node's native TS loader cannot remap .js specifiers to .ts source at script runtime.

interface PresetRulesOptions {
  readonly includeBuiltIn?: boolean;
}

// Maps manifest severity to the two-value oxlint preset severity (info and warning both collapse to warn).
export const oxlintSeverityForManifestEntry = (entry: RuleManifestEntry): 'error' | 'warn' =>
  entry.severity === 'error' ? 'error' : 'warn';

// Returns preset-enabled manifest entries for the given domains without plugin prefixes.
// Preset assemblers should call pluginRuleName on each result to build rule config keys.
// Scripts and tests can use entry.name values directly without any plugin prefix.
export const presetEntriesForDomains = (
  domains: ReadonlyArray<RuleDomain>,
  { includeBuiltIn = false }: PresetRulesOptions = {},
): ReadonlyArray<RuleManifestEntry> =>
  ruleManifest.filter(
    (entry) =>
      domains.includes(entry.domain) &&
      entry.presetEnabled &&
      (includeBuiltIn || entry.disposition !== 'built-in'),
  );
