// Renders the collected rule list as docs/references/rules.md. The page is fully generated: the
// renderer owns every byte, and `pnpm rules-page:check` compares the committed file against it.

import {
  type CollectedRule,
  type RuleActivation,
  type RuleList,
  type RuleSource,
  ruleSources,
} from './rule-list.ts';

const sourceHeadings: Readonly<Record<RuleSource, string>> = {
  oxlint: 'Built-in oxlint rules',
  package: 'Package rules',
  tsgo: 'tsgo rules',
};

const sourceIntros: Readonly<Record<RuleSource, string>> = {
  oxlint:
    'Built-in rules come from `oxlint --print-config` on `baseConfig` and on the base, Vitest, and Node runtime composition, plus the built-in rules a preset sets explicitly.',
  package:
    'Rules this package implements. What it catches is the manifest note; the fix is the rule message.',
  tsgo: 'Rules delegated to `@effect/tsgo`, which run only on the patched oxlint route. Descriptions are the upstream text; tsgo rules the policy sets off everywhere are not listed.',
};

// Splitting on backticks alternates prose and code-span segments, starting with prose.
const segmentKinds = 2;

const tableHeader = [
  '| Rule | Presets and configs | Severity | What it catches | Docs |',
  '| --- | --- | --- | --- | --- |',
];

// Markdown table cells: pipes must be escaped everywhere, including inside code spans, and a raw
// `<` outside a code span would start an HTML tag, so only prose segments escape it.
const escapeCell = (text: string): string =>
  text
    .replaceAll(/\s+/gu, ' ')
    .split('`')
    .map((segment, index) => {
      const pipesEscaped = segment.replaceAll('|', String.raw`\|`);
      return index % segmentKinds === 0 ? pipesEscaped.replaceAll('<', '&lt;') : pipesEscaped;
    })
    .join('`');

const severityText = (activation: RuleActivation): string =>
  activation.normal === activation.test
    ? activation.normal
    : `${activation.normal} / ${activation.test}`;

// One severity when every target agrees; otherwise each target's severity on its own line.
const severityCell = (activations: readonly RuleActivation[]): string => {
  const texts = [...new Set(activations.map(severityText))];
  if (texts.length === 1) {
    return texts[0] ?? '';
  }
  return activations
    .map((activation) => `\`${activation.target}\`: ${severityText(activation)}`)
    .join('<br>');
};

const descriptionCell = (rule: CollectedRule): string => {
  if (rule.source === 'package') {
    return escapeCell(`${rule.description ?? ''} **Fix:** ${rule.fix ?? ''}`);
  }
  if (rule.description !== null) {
    return escapeCell(rule.description);
  }
  return rule.category === null ? '' : `Category: \`${rule.category}\`.`;
};

const docsCell = (rule: CollectedRule): string => {
  if (rule.docsUrl !== null) {
    return `[docs](${rule.docsUrl})`;
  }
  return rule.reference === null ? '' : escapeCell(`Ref: ${rule.reference}`);
};

const ruleRow = (rule: CollectedRule): string =>
  [
    '',
    `\`${rule.name}\``,
    rule.activations.map((activation) => `\`${activation.target}\``).join(', '),
    severityCell(rule.activations),
    descriptionCell(rule),
    docsCell(rule),
    '',
  ]
    .join(' | ')
    .trim();

const sourceSection = (source: RuleSource, rules: readonly CollectedRule[]): readonly string[] => [
  '',
  `## ${sourceHeadings[source]} (${rules.length})`,
  '',
  sourceIntros[source],
  '',
  ...tableHeader,
  ...rules.map(ruleRow),
];

const pageHeader = (list: RuleList): readonly string[] => [
  '# Rules reference',
  '',
  '<!-- Generated by `pnpm gen:rules-page` from scripts/checks/generate-rules-page.ts. Do not edit by hand. -->',
  '',
  'This page lists every rule that at least one shipped preset or config turns on. It is generated from the rule manifest, the pinned `@effect/tsgo` policy, and the root oxlint engine. Regenerate it with `pnpm gen:rules-page`; `pnpm check` fails when it is stale. To search and filter the same list, run `pnpm rules:view`.',
  '',
  'Severity reads `normal / tests` when test files differ, where tests means files that match the test-file overrides. The presets, configs, and compositions are:',
  '',
  ...list.targets.map((target) => `- \`${target}\``),
  '',
  `The tsgo descriptions come from \`@effect/tsgo\` ${list.tsgoVersion} (${list.tsgoAttribution}).`,
];

export const renderRulesMarkdown = (list: RuleList): string =>
  `${[
    ...pageHeader(list),
    ...ruleSources.flatMap((source) =>
      sourceSection(
        source,
        list.rules.filter((rule) => rule.source === source),
      ),
    ),
  ].join('\n')}\n`;
